GET http://localhost:3000/users/id/transactions HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJjdXN0b21lck4iLCJ1c2VySWQiOjEsInJvbGUiOiJjdXN0b21lciIsImxhc3ROYW1lIjoiY3VzdG9tZXJMIiwiYXZhdGFyIjoiYW5vbi5wbmciLCJkaXNwbGF5TmFtZSI6ImN1c3RvbWVyRE4iLCJiYWxhbmNlIjoiMCIsImVtYWlsIjoiY3VzdG9tZXJAbWFpbC5jb20iLCJyYXRpbmciOjAsImlhdCI6MTY5NDA5OTYxNCwiZXhwIjoxNjk0MTAzMjE0fQ.iVc13GHUh0g3ZErVo43w632G0qzSe7uybNXOV3uaONY