GET http://localhost:3000/users/id/transactions HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJjdXN0b21lck4iLCJ1c2VySWQiOjEsInJvbGUiOiJjdXN0b21lciIsImxhc3ROYW1lIjoiY3VzdG9tZXJMIiwiYXZhdGFyIjoiYW5vbi5wbmciLCJkaXNwbGF5TmFtZSI6ImN1c3RvbWVyRE4iLCJiYWxhbmNlIjoiMCIsImVtYWlsIjoiY3VzdG9tZXJAbWFpbC5jb20iLCJyYXRpbmciOjAsImlhdCI6MTY5NDI0MDc5NSwiZXhwIjoxNjk0MjQ0Mzk1fQ.eTSbI5JR7tGwvEL6u4a9dQE3G1cQBpxxuXP383ax95E